# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10hxgZRvsM221zKNWkdJx7rZsELEzU4d5
"""

import numpy as np
import streamlit as st
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt


# Correct file paths (update these paths based on your verification step)
generator_path = "C:/Users/saina/Downloads/generator.keras"
discriminator_path = "C:/Users/saina/Downloads/discriminator.keras"
cgan_path = "C:/Users/saina/Downloads/cgan.keras"

# Load the trained generator model
generator = load_model(generator_path)

# Define categories
categories = ['Angry', 'Happy', 'Sad', 'Neutral', 'Surprise', 'Ahegao']

# Set latent dimension and number of classes
latent_dim = 100
num_classes = len(categories)

# Streamlit interface
st.title("Face Expression Generator using cGAN")

expression = st.selectbox("Select an expression", categories)
if st.button("Generate Face"):
    noise = np.random.normal(0, 1, (1, latent_dim))
    label = np.array([categories.index(expression)]).reshape(-1, 1)
    gen_img = generator.predict([noise, label])
    gen_img = 0.5 * gen_img + 0.5

    fig, ax = plt.subplots()
    ax.imshow(gen_img[0])
    ax.axis('off')
    st.pyplot(fig)

